import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://2ndhappiness.com'
  const pages = [
    '',
    '/about',
    '/after-death',
    '/after-hospital',
    '/asset',
    '/care-cost-split',
    '/care-items',
    '/care-level',
    '/care-manager-relation',
    '/care-resignation',
    '/care-timing',
    '/caregiver-mental-care',
    '/checklist',
    '/choice-failure-lessons',
    '/contact',
    '/cost',
    '/dementia-care-basics',
    '/dementia-facility',
    '/disclaimer',
    '/end-of-life-at-home',
    '/editorial-policy',
    '/ending-activity',
    '/facility-vs-home-care',
    '/family-visit-rhythm',
    '/faq',
    '/for-you',
    '/funeral',
    '/funeral-guide',
    '/home-care',
    '/how-to-choose',
    '/insurance-gap',
    '/insurance-usage-guide',
    '/parents-support',
    '/post-admission-money',
    '/pref-cost-ranking',
    '/prepare',
    '/privacy',
    '/process',
    '/ranking',
    '/reason',
    '/retirement-cost',
    '/review-guide',
    '/room-size-cost',
    '/sakouju',
    '/sibling-care-discussion',
    '/simulation',
    '/tell-parents',
    '/tokuyou-waiting',
    '/transport',
    '/types',
    '/zero-initial-fee',
  ]
  const lowPriorityPages = ['/about', '/disclaimer', '/privacy', '/contact', '/editorial-policy']
  return pages.map((page) => ({
    url: `${baseUrl}${page}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: page === '' ? 1 : lowPriorityPages.includ